token: "*********************************"
logFile: "../logs.log"
unwrittenDataFile: "../unwritten_data.json"
accessChatID: -11111111
adminsTgChatID: 11111111
linkToDB: "postgres://username:password@localhost:5432/database_name"
queries:
      addUser: "INSERT INTO public.\"users\" (tg_user_id, tg_user_name, active_user) VALUES ($1, $2, $3);"
      editUser: "UPDATE public.\"users\" SET active_user=$1 WHERE tg_user_id=$2;"
      addMessage: "INSERT INTO public.\"messages\" (message_id, date, text, is_edit, user_id) VALUES ($1, $2, $3, $4, (SELECT id FROM public.\"users\" WHERE tg_user_id = $5));"
      editMessage: "UPDATE public.\"messages\" SET text=$1, is_edit=$2 WHERE message_id=$3;"
      getUser:  "SELECT id FROM public.users WHERE tg_user_id=$1"